server:
  port: 84

eureka:
  client:
    #是否将自己注册到注册中心, 默认true
    register-with-eureka: true
    #    #是否从EurekaServer抓取已有的注册信息,单机无所谓,集群必须设置为true配合ribbon使用负载均衡
    #    fetch-registry: true
    service-url:
      #defaultZone: http://eureka7001.com:7001/eureka  #单机版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版
spring:
  application:
    #微服务名称 此处的名称即为注册发现中心的名称
    name: cloud-consummer-feign-hystrix-order

ribbon:
  #读取时间
  ReadTimeout:  5000
  #连接时间
  ConnectTimeout: 5000